### ISSUE TITLE
Compilation guide?

### ISSUE THREAD

**Issue by ghost** [purplemarshmallow/z64#4] opened 2016-03-03 11:15 UTC
Hi, 
I was wondering if there is any compilation guide or instructions. 
I want to try out some things in a private fork, and I was wondering how to compile this.

Thanks.

**Comment by purplemarshmallow** [comment] 2016-03-03 20:43
I compile with Visual Studio
You open z64.sln and press F7 and it should build without problems. But you need to have correct version of SDL.dll (1.2.15) and the glew32.dll (1.13) in the emulator's directory or the plugin may not work

There's also a makefile in the repo but I never tried to use it

**Comment by cxd4** [comment] 2016-03-06 22:20
My compilation instructions:

```
cd z64/src
make
?!?!?!?!
PROFIT!
```

The Makefile can be used this way on Windows as well (either with MSVC or MinGW), but executing `make` on Windows requires a little more than just a minimalist, manual MinGW installation to get it to work.  I also dislike `Makefile`s and prefer shell scripts (`*.sh`), but no point in fighting pre-existing ones.

**Comment by cxd4** [comment] 2016-03-07 08:25
Seeing as the original poster of this issue has deleted its own GitHub account and can no longer respond/close this issue, I think I would probably just close it myself.  People can still post after the issue is closed, but it's solved because any traditional build method works now without README deviations.

**Closed as completed** 2016-03-09 06:07 UTC
